//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buildeeji.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyIMage
    {
        public string PropertyImageName { get; set; }
        public int PropertID { get; set; }
        public string PropertyImageCategory { get; set; }
        public string PropertyImagePath { get; set; }
    }
}
