//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buildeeji.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyDetail
    {
        public int PropertyDetailsId { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public string SubCategoryDescription { get; set; }
        public string PropertyAmenityID { get; set; }
        public Nullable<int> Bedrroms { get; set; }
        public Nullable<int> Washrooms { get; set; }
        public Nullable<int> Balcony { get; set; }
        public Nullable<int> FloorNUmber { get; set; }
        public Nullable<int> TotalFloors { get; set; }
    }
}
